from typing import Self

def probe_version() -> str: ...

class ResourceSnapshot:
    rss_bytes: int
    vms_bytes: int
    open_fds: int
    timestamp_ns: int
    def rss_mb(self) -> float: ...
    def vms_mb(self) -> float: ...

class BackgroundSampler:
    def __new__(cls) -> Self: ...
    def start(self, interval_ms: int) -> None: ...
    def stop(self) -> int: ...

def snapshot_resources() -> ResourceSnapshot: ...
def list_open_fds() -> list[str]: ...
def register_signal_pipe(signal_num: int) -> tuple[int, int]: ...
